sudo: false

language: c

addons:
  apt:
    packages:
    - libgmp-dev

env:
  - ARGS="--resolver lts-6.10"
  - ARGS="--resolver nightly-2016-08-25"

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --no-terminal setup $ARGS

install:
  - stack --no-terminal $ARGS setup
  - stack $ARGS ghc -- --version

script:
  - stack --no-terminal $ARGS test

cache:
  directories:
  - $HOME/.stack
